apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
