apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
